/**
 * @module app
 * @description The express app.
 * @requires express
 * @requires morgan
 * @requires routes/home.route
 * @requires routes/news.route
 * @requires routes/contact.route
 */

const express = require("express");
const morgan = require("morgan");

/**
 * @name app
 * @type {Object}
 * @description The express app object that is generated by the express function.
 *
 * @see https://expressjs.com/en/4x/api.html#app
 */
const app = express();

/**
 * @name app.use
 * @type {Function}
 * @description morgan - Middleware function to log HTTP requests
 * @description express.urlencoded - Middleware function to parse incoming requests with urlencoded payloads
 *
 * @see https://www.npmjs.com/package/morgan
 * @see https://expressjs.com/en/4x/api.html#app.use
 */
app.use(morgan("dev"));
app.use(express.urlencoded({ extended: true })); // translate with an incoming POST request what is inside req.body

/**
 * @name app.use
 * @type {Function}
 * @param {String} path - The path on which a router is mounted
 * @param {Function} router - The router
 *
 * @description Middleware function to mount the router on the path
 * @description The router handles the requests to the path and any sub-paths
 *
 * @see https://expressjs.com/en/4x/api.html#app.use
 */
app.use("/", require("../routes/home.route"));
app.use("/newsletter", require("../routes/news.route"));

module.exports = app;
